#!/bin/bash

echo "#!/bin/bash" > $1
echo $2 >> $1

#check if file is executable
if ! [[ -x $1 ]] 
then
	chmod u+x $1
	MESSAGE="Added script for task $3"
else
	MESSAGE="Fixed error in script"
fi

git add .
git commit -m "MESSAGE"
git push
